packages:
  - apps/*
  - functions/*
  - packages/*
  - libs/*
  - tools/*
  - examples/*
allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAge: 0
overrides:
  brace-expansion@<1.1.18: ^1.1.18
  fast-uri@>=3.0.0 <3.1.6: ^3.1.6
  nanoid@<3.3.18: ^3.3.18
  postcss@<=8.5.17: ^8.5.18
